imports:
    - { resource: config.yml }

framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar:             false
    intercept_redirects: false

doctrine:
    orm:
        metadata_cache_driver: apc
        query_cache_driver:    apc
        result_cache_driver:   apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      syslog
