jms_security_extra:
    secure_all_services: false
    expressions:         true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users: %users%

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        # In dev environment.
        wdt:
            pattern:  ^/_wdt
            security: false

        main:
            anonymous:  false
            http_basic:
                realm: "Cackatoo"

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
