#!/bin/sh

set -e

CACHEDIR="/var/cache/cackatoo"
LOGDIR="/var/log/cackatoo"

for dir in $CACHEDIR $LOGDIR; do
    if [ ! -d $dir ]; then
        mkdir $dir
        chown puppet:puppet $dir
        chmod 750 $dir
    fi
done



# TODO Warm up cache (app/console cache:clear).



# And start services...
# TODO Configured (/etc/defaults/project)? No? Check, and not start services!
invoke-rc.d php5-fpm reload

# TODO And remove old cache (all folders except for current version).
